### ISSUE TITLE
Orientation changes fails to highlight constraint warning

### ISSUE THREAD

**Issue by JulesMoorhouse** [yext/YXTUnsatisfiableConstraintsDetector#1]
When I change the orientation of my app in the simulator and have the UIViewAlertForUnsatisfiableConstraints breakpoint enabled, Xcode catches the constraint warning.

However YXTUnsatisfiableConstraintsDetector doesn't catch this.

Oddly actually looking at each orientation upon starting the app (in the simulator) doesn't cause the breakpoint to hit.

I use fastlane snapshot to produce a complete picture of any constraint errors, as part of my ui tests I perform a rotation, YXTUnsatisfiableConstraintsDetector doesn't capture the warning.

Can this be added / fixed ?

**Comment by theothertomelliott** [comment]
Sorry I didn't get around to this one sooner. This project hasn't been active for a little while, but we'd welcome pull requests if you're in a position to implement this sort of thing.

**Comment by JulesMoorhouse** [comment]
I worked around this I believe, I’m not sure how to reproduce this now.

Thanks.

**Comment by theothertomelliott** [comment]
Ok, I'll mark this closed for now. Please reopen if you see it again.
