### ISSUE TITLE
Build input file cannot be found: - build error

### ISSUE THREAD

**Issue by JulesMoorhouse** [yext/YXTUnsatisfiableConstraintsDetector#2]
: - 1: Build input file cannot be found: '/Users/jm/Library/Developer/Xcode/DerivedData/MyApp-ffjzwfulkrjgewalqivwlkizaqom/Build/Products/Debug-iphoneos/YXTUnsatisfiableConstraintsDetector/YXTUnsatisfiableConstraintsDetector.bundle/YXTUnsatisfiableConstraintsDetector'

I keep getting this build error, any ideas?

**Comment by theothertomelliott** [comment]
This might be because this project uses an older format. Switching to legacy build format may help:
https://stackoverflow.com/questions/52401856/problems-after-upgrading-to-xcode-10-build-input-file-cannot-be-found
Caveat that I've not reproduced or tested this myself.

**Comment by JulesMoorhouse** [comment]
Cheers
